[build]
  functions = "functions"

# For /api exactly
[[redirects]]
from = "/api"
to = "/.netlify/functions/api"
status = 200

# For /api/*
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
